# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-31 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_summercampactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='summercampactivities',
            name='participants',
            field=models.ManyToManyField(related_name='my_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
